export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const ERROR_MSG = "ERROR_MSG"
export const RENT_BICYCLE = "RENT_BICYCLE"
export const CHANG_LEASE_STATUS = "CHANG_LEASE_STATUS"
export const INIT_ORDER = "INIT_ORDER"
export const INIT_BICYCLE = "INIT_BICYCLE"
export const INIT_USER = "INIT_USER"

export const GET_ORDER_LIST = "GET_ORDER_LIST"
export const GET_ORDER_LIST_MORE = "GET_ORDER_LIST_MORE"



