export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const ERROR_MSG = "ERROR_MSG"
export const RENT_BICYCLE = "RENT_BICYCLE"
export const CHANG_LEASE_STATUS = "CHANG_LEASE_STATUS"
export const INIT_BICYCLE = "INIT_BICYCLE"


